In [1]:
import numpy as np
import time

In [2]:
A = np.eye(10)*10 + np.random.randint(1, 10, size = (10, 10))
A

array([[11.,  2.,  2.,  2.,  1.,  3.,  9.,  9.,  2.,  3.],
       [ 7., 19.,  5.,  1.,  6.,  3.,  9.,  4.,  8.,  8.],
       [ 6.,  1., 12.,  7.,  8.,  8.,  1.,  9.,  2.,  9.],
       [ 3.,  5.,  8., 19.,  1.,  1.,  1.,  6.,  8.,  7.],
       [ 1.,  5.,  6.,  5., 11.,  6.,  5.,  2.,  8.,  5.],
       [ 1.,  6.,  9.,  7.,  5., 14.,  1.,  5.,  3.,  4.],
       [ 1.,  8.,  2.,  9.,  1.,  1., 14.,  3.,  9.,  6.],
       [ 5.,  2.,  6.,  8.,  6.,  8.,  5., 13.,  6.,  6.],
       [ 3.,  6.,  2.,  7.,  2.,  6.,  3.,  6., 18.,  5.],
       [ 8.,  6.,  2.,  4.,  9.,  6.,  9.,  8.,  4., 18.]])

In [3]:
A[np.arange(9), np.arange(1, 10)] += 10
A

array([[11., 12.,  2.,  2.,  1.,  3.,  9.,  9.,  2.,  3.],
       [ 7., 19., 15.,  1.,  6.,  3.,  9.,  4.,  8.,  8.],
       [ 6.,  1., 12., 17.,  8.,  8.,  1.,  9.,  2.,  9.],
       [ 3.,  5.,  8., 19., 11.,  1.,  1.,  6.,  8.,  7.],
       [ 1.,  5.,  6.,  5., 11., 16.,  5.,  2.,  8.,  5.],
       [ 1.,  6.,  9.,  7.,  5., 14., 11.,  5.,  3.,  4.],
       [ 1.,  8.,  2.,  9.,  1.,  1., 14., 13.,  9.,  6.],
       [ 5.,  2.,  6.,  8.,  6.,  8.,  5., 13., 16.,  6.],
       [ 3.,  6.,  2.,  7.,  2.,  6.,  3.,  6., 18., 15.],
       [ 8.,  6.,  2.,  4.,  9.,  6.,  9.,  8.,  4., 18.]])

In [4]:
X = np.random.randint(1, 10, size = (1, 10))
X

array([[3, 4, 6, 4, 5, 5, 1, 4, 3, 6]])

In [5]:
B = A.dot(X.T)
B

array([[190.],
       [333.],
       [339.],
       [304.],
       [281.],
       [268.],
       [222.],
       [302.],
       [284.],
       [312.]])

In [6]:
# band = True, если матрица трехдиагональная, если нет, то band = False
# norm = True, если матрица нормированна, если нет, то band = False
# size_matrix - размер матрицы
def create_matrix(size_matrix = 10, band = False, norm = False):
    A = np.eye(size_matrix)*10 + np.random.randint(1, 10, size = (size_matrix, size_matrix))   
    if band: 
        A = np.zeros((size_matrix, size_matrix))
        A[np.arange(size_matrix-1), np.arange(1, size_matrix)] += np.random.randint(1, 20)
        A[np.arange(size_matrix), np.arange(size_matrix)] += np.random.randint(1, 20)
        A[np.arange(1, size_matrix), np.arange(size_matrix-1)] += np.random.randint(1, 20)
    if norm:
        A += np.eye(size_matrix)*90
    X = np.random.randint(1, 10, size = (1, size_matrix))
    B = A.dot(X.T)
    return A, X, B

## Метод Гаусса



In [7]:
# matr_coef - матрица А размерностью n x n
# separ_column - столбец B размерностью n x 1
def method_Gauss(matr_coef, separ_column): 
    n = separ_column.shape[0]
    matr_coef = np.hstack([matr_coef, separ_column])  
    # прямой ход 
    for k in range(n):
        div = matr_coef[k, k]
        for i_str in range(k, n+1):
            matr_coef[k, i_str] /= div
        
        for j_str in range(k+1, n):
            matr_coef[j_str, :] -= matr_coef[j_str, k] * matr_coef[k, :]

    # обратный ход
    i = n - 1
    while i > 0:
        j = i - 1
        while j >= 0:
            matr_coef[j][n] = matr_coef[j][n] - matr_coef[j][i] * matr_coef[i][n] 
            j -= 1
        i -= 1    
    return matr_coef[:, n]

In [8]:
start = time.time()
A, X, B = create_matrix(1000)
display(A, B)
x_d = method_Gauss(A, B)
end = time.time()
display(abs(X - x_d).max(), abs(X - x_d).min())
display(abs(B.T - A.dot(x_d.T)).max(), abs(B.T - A.dot(x_d.T)).min())
display(end - start)

array([[13.,  7.,  6., ...,  9.,  1.,  3.],
       [ 8., 18.,  6., ...,  1.,  6.,  9.],
       [ 9.,  8., 16., ...,  7.,  8.,  5.],
       ...,
       [ 7.,  1.,  7., ..., 19.,  3.,  8.],
       [ 3.,  1.,  3., ...,  6., 15.,  1.],
       [ 1.,  8.,  9., ...,  2.,  2., 14.]])

array([[24580.],
       [24454.],
       [24367.],
       [24558.],
       [24309.],
       [24841.],
       [24348.],
       [24957.],
       [25282.],
       [23848.],
       [24305.],
       [24396.],
       [23496.],
       [24745.],
       [25193.],
       [24299.],
       [25004.],
       [24761.],
       [24299.],
       [24297.],
       [24526.],
       [23937.],
       [24370.],
       [25611.],
       [24783.],
       [23922.],
       [25080.],
       [24550.],
       [23496.],
       [25016.],
       [24848.],
       [24587.],
       [24986.],
       [24214.],
       [23699.],
       [24586.],
       [24693.],
       [24346.],
       [25031.],
       [24890.],
       [23568.],
       [23923.],
       [24277.],
       [25066.],
       [24399.],
       [24854.],
       [25139.],
       [24842.],
       [24164.],
       [25281.],
       [24424.],
       [24151.],
       [24046.],
       [24263.],
       [24565.],
       [24515.],
       [23938.],
       [24587.],
       [24525.

2.718344660479488e-09

2.4513724383723456e-13

1.5410478226840496e-08

0.0

7.402036666870117

# Метод прогонки

In [9]:
def sweep_method(size):
    start = time.time()
    A, X, B = create_matrix(size, 1)
    X_diff = TDMA(A, B)
    end = time.time()
    dB = abs(B - A.dot(X_diff.reshape(size, 1)))
    dX = abs(X - X_diff)
    return A, X, B, dX.min(), dX.max(), dB.min(), dB.max(), end - start

In [10]:
# n - число уравнений (строк матрицы)
# b - диагональ, лежащая над главной (нумеруется: [0;n-2])
# c - главная диагональ матрицы A (нумеруется: [0;n-1])
# a - диагональ, лежащая под главной (нумеруется: [1;n-1])
# B - правая часть (столбец)
# x - решение, массив x будет содержать ответ
def TDMA(A,B):
    a = np.hstack([0, A.diagonal(-1)])
    b = np.hstack([A.diagonal(1), 0])
    c = A.diagonal()
    
    n = B.shape[0]
    P_mas = np.zeros(n)
    Q_mas = np.zeros(n)    
    P_mas[0] = -b[0] / c[0]
    Q_mas[0] = B[0] / c[0]
    x = np.zeros(n)

    for i in range(1, n):
        P_mas[i] = -b[i]/(a[i]*P_mas[i-1] + c[i])
        Q_mas[i] = (B[i] - a[i]*Q_mas[i-1])/(a[i]*P_mas[i-1] + c[i])
    
    x[n-1] = Q_mas[n - 1]
    for i in range(n-1, 0, -1):
        x[i - 1] = P_mas[i - 1]*x[i] + Q_mas[i - 1]

    return x

In [11]:
sweep_method(1000)

(array([[17., 18.,  0., ...,  0.,  0.,  0.],
        [ 9., 17., 18., ...,  0.,  0.,  0.],
        [ 0.,  9., 17., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  0., ..., 17., 18.,  0.],
        [ 0.,  0.,  0., ...,  9., 17., 18.],
        [ 0.,  0.,  0., ...,  0.,  9., 17.]]),
 array([[1, 4, 8, 4, 1, 1, 8, 6, 5, 7, 5, 2, 6, 9, 4, 4, 3, 7, 9, 9, 3, 2,
         7, 6, 6, 9, 4, 9, 4, 2, 6, 7, 5, 3, 5, 4, 7, 4, 2, 4, 8, 8, 3, 1,
         8, 4, 3, 4, 1, 3, 3, 4, 9, 6, 9, 1, 6, 3, 8, 5, 5, 4, 7, 1, 7, 1,
         2, 6, 1, 3, 6, 3, 6, 3, 4, 3, 8, 7, 6, 4, 5, 8, 6, 1, 8, 1, 8, 3,
         2, 8, 8, 5, 5, 3, 8, 9, 7, 7, 6, 7, 5, 9, 6, 9, 3, 2, 6, 2, 2, 1,
         5, 8, 6, 2, 5, 3, 9, 4, 6, 2, 7, 2, 7, 6, 3, 4, 7, 9, 3, 6, 8, 1,
         4, 5, 7, 1, 7, 1, 6, 3, 2, 7, 3, 4, 6, 6, 1, 4, 2, 4, 4, 7, 1, 6,
         3, 4, 8, 2, 6, 9, 5, 1, 6, 2, 5, 6, 8, 9, 4, 9, 1, 8, 3, 7, 2, 1,
         2, 5, 6, 8, 8, 4, 7, 8, 2, 5, 6, 6, 4, 2, 5, 6, 9, 8, 4, 1, 5, 8,
         8, 3, 1, 9, 8, 6, 5, 4, 9, 8, 1

# Метод простых итераций

In [20]:
def iterations(eps, A, B, X):
    n = A.shape[0]
    A_new = np.hstack([A, B])
    for i in range(n):
        coef = A_new[i, i]
        A_new[i, :] /= coef
        
    A = A_new[:, :n]
    B = A_new[:, n].reshape(-1, 1)
    A_new = np.eye(n) - A
    X_0 = np.vstack([B.T, B.T + A_new.dot(B).T])
    i = 1
    while 1:
        X_0 = np.vstack([X_0, B.T + A_new.dot(X_0[i, :]).T])
        i += 1
        if abs(X_0[i, :] - X).sum()  < n*eps:
            break
    return X_0[i, :], i

def iter_method(eps, n):
    start = time.time()
    A, X, B = create_matrix(n, 0, 1)
    X_diff, n_iter = iterations(eps, A, B, X)
    dB = abs(B - A.dot(X_diff.reshape(n, 1)))
    dX = abs(X - X_diff)
    end = time.time()
    return dX.min(), dX.max(), dB.min(), dB.max(), n_iter, end-start    

In [23]:
for i in [1e-4, 1e-8, 1e-12]:
    for j in [10, 20]:
        dX_min, dX_max, dB_min, dB_max, n_iter, time_ = iter_method(i, j)
        print(i, j)
        print('dX_min, dX_max, dB_min, dB_max, n_iter, time', dX_min, dX_max, dB_min, dB_max, n_iter, time_)

0.0001 10
dX_min, dX_max, dB_min, dB_max, n_iter, time 3.389711759727021e-05 6.207182503992215e-05 0.005177599931130317 0.009421371147027457 13 0.0
0.0001 20
dX_min, dX_max, dB_min, dB_max, n_iter, time 8.034260913269975e-05 0.0001164096315555696 0.015889623134171416 0.022364925345755182 88 0.015999317169189453
1e-08 10
dX_min, dX_max, dB_min, dB_max, n_iter, time 4.3048835607351066e-09 8.021510122802056e-09 6.564198997693893e-07 1.176984596895636e-06 24 0.0
1e-08 20
dX_min, dX_max, dB_min, dB_max, n_iter, time 7.952710490144455e-09 1.0871648470356376e-08 1.5992740145520656e-06 2.1842449768882943e-06 181 0.016001462936401367
1e-12 10
dX_min, dX_max, dB_min, dB_max, n_iter, time 3.8191672047105385e-13 5.773159728050814e-13 5.4228621593210846e-11 8.606093615526333e-11 30 0.0
1e-12 20
dX_min, dX_max, dB_min, dB_max, n_iter, time 7.638334409421077e-13 1.0960121699099545e-12 1.5074874681886286e-10 2.18506102100946e-10 229 0.016001462936401367


In [ ]:
all(np.array([1, 2, 3]) - np.array([1, 2, 3])) > 0